### ISSUE TITLE
Schema migration - tracking issue

### ISSUE THREAD

**Issue by MarinPostma** [tursodatabase/libsql#1123]
implements the happy path of schema migration. do not use this feature yet.

Here a list of remaining work to get schema migration working properly:
- [ ] move all the migration-related stuff from the meta_store to the schema module; let the scheduler use its own connection to the meta store.
- [ ] move the schema for the meta store to a sqlite file, and `include!` that file for clarity
- [ ] perform error handling, check migration success status, use custom QueryResultHandler to collect results
- [ ] ensure that the temp table `enqueued_tasks` is updated corectly after a task is popped when a tasks status changed (maybe use a trigger?)
- [ ] handle abort; first when a dry run failed, then if a user abort the migration before the dry-run is complete
- [ ] prevent a job from being enqueued if there is still a pending job for that namespaces
- [ ] Add loads of tests, and test load
- [ ] prevent writes while there is are pending jobs in a database
- [ ] sync database before starting migration
- [ ] sync meta store after enqueue job
- [ ] track version schema
- [ ] go through all todos that I left in the code

**Comment by haaawk** [comment]
what's also missing I think is cloning schema to newly created db that links to existing schema

**Comment by MarinPostma** [comment]
Add whatever you can think of to the list
