### ISSUE TITLE
Tracking issues of adding more storage services support for bottomless

### ISSUE THREAD

**Issue by Xuanwo** [tursodatabase/libsql#887]
RFC: https://github.com/libsql/sqld/issues/711

This issues is used to track works towards adding more storage services support for bottomless. We will perform some refactor first to allow us to adding more logic here.

## Tasks

- [ ] https://github.com/tursodatabase/libsql/pull/888
- [ ] Add [opendal](https://github.com/apache/incubator-opendal) for gcs support.
- [ ] Add [opendal](https://github.com/apache/incubator-opendal) for azblob support.
- [ ] Polish docs
- [ ] Tests (how we test s3 operations for now?)
- [ ] Release!

**Comment by Xuanwo** [comment]
cc @psarna for comments and feel free to update the tasks list!

**Comment by Xuanwo** [comment]
Based on the feedback from https://github.com/tursodatabase/libsql/pull/888#issuecomment-1887357907, this issue is not valid anymore.
